services:
  - type: web
    name: cerebra-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: WIKI_CONTACT_EMAIL
        sync: false
      - key: WIKI_GITHUB_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
